{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "gpuType": "T4",
      "authorship_tag": "ABX9TyPXCPgnj3iQBctnkguYIar1"
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    },
    "accelerator": "GPU"
  },
  "cells": [
    {
      "cell_type": "code",
      "source": [
        "# ============================================================================\n",
        "# MENTAL HEALTH MOOD TRACKER - MODEL 1: DREADDIT STRESS DETECTION\n",
        "# Fine-tune MentalRoBERTa for Binary Stress Classification\n",
        "# ============================================================================\n",
        "\n",
        "# CELL 1: Install Dependencies\n",
        "# ============================================================================\n",
        "\n",
        "!pip install transformers datasets torch scikit-learn pandas numpy\n",
        "!pip install accelerate scipy\n",
        "\n",
        "print(\"✅ Dependencies installed successfully!\")"
      ],
      "metadata": {
        "id": "Chzb5z6DLzjA"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "\n",
        "# ============================================================================\n",
        "# CELL 2: Import Libraries\n",
        "# ============================================================================\n",
        "\n",
        "import pandas as pd\n",
        "import numpy as np\n",
        "from sklearn.model_selection import train_test_split\n",
        "from sklearn.metrics import accuracy_score, precision_recall_fscore_support, confusion_matrix, classification_report\n",
        "import torch\n",
        "from transformers import AutoTokenizer, AutoModelForSequenceClassification, TrainingArguments, Trainer\n",
        "from datasets import Dataset\n",
        "import matplotlib.pyplot as plt\n",
        "import seaborn as sns\n",
        "from datetime import datetime\n",
        "import json\n",
        "from datasets import Dataset\n",
        "# Check GPU availability\n",
        "device = torch.device(\"cuda\" if torch.cuda.is_available() else \"cpu\")\n",
        "print(f\"\\n🖥️  Device: {device}\")\n",
        "if torch.cuda.is_available():\n",
        "    print(f\"GPU Name: {torch.cuda.get_device_name(0)}\")\n",
        "    print(f\"GPU Memory: {torch.cuda.get_device_properties(0).total_memory / 1e9:.2f} GB\")"
      ],
      "metadata": {
        "id": "d2tDvjXTMJNV"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "\n",
        "\n",
        "# ============================================================================\n",
        "# CELL 3: Upload and Load DREADDIT Dataset\n",
        "# ============================================================================\n",
        "\n",
        "from google.colab import files\n",
        "\n",
        "print(\"📁 Step 1: Upload your Training CSV file (with 'text' and 'label' columns)\")\n",
        "uploaded_train = files.upload()\n",
        "train_filename = list(uploaded_train.keys())[0]\n",
        "train_df_raw = pd.read_csv(train_filename)\n",
        "print(f\"✅ Uploaded Training file: {train_filename} | Shape: {train_df_raw.shape}\")\n",
        "\n",
        "print(\"\\n📁 Step 2: Upload your Testing CSV file (with 'text' and 'label' columns)\")\n",
        "uploaded_test = files.upload()\n",
        "test_filename = list(uploaded_test.keys())[0]\n",
        "test_df_raw = pd.read_csv(test_filename)\n",
        "print(f\"✅ Uploaded Testing file: {test_filename} | Shape: {test_df_raw.shape}\")\n"
      ],
      "metadata": {
        "id": "9DxckhA4SWJE"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "\n",
        "# ============================================================================\n",
        "# CELL 4: Explore DREADDIT Dataset\n",
        "# ============================================================================\n",
        "def explore_dataset(df):\n",
        "  print(\"\\n\" + \"=\"*60)\n",
        "  print(\"DATASET EXPLORATION\")\n",
        "  print(\"=\"*60)\n",
        "\n",
        "  # Check for missing values\n",
        "  print(f\"\\nMissing values:\")\n",
        "  print(df.isnull().sum())\n",
        "\n",
        "  # Check data types\n",
        "  print(f\"\\nData types:\")\n",
        "  print(df.dtypes)\n",
        "\n",
        "  # Label distribution\n",
        "  print(f\"\\n Label Distribution:\")\n",
        "  label_dist = df['label'].value_counts()\n",
        "  print(label_dist)\n",
        "  print(f\"\\nPercentage:\")\n",
        "  print(df['label'].value_counts(normalize=True) * 100)\n",
        "\n",
        "# Text length statistics\n",
        "  df['text_length'] = df['text'].str.len()\n",
        "  print(f\"\\n📏 Text Length Statistics:\")\n",
        "  print(df['text_length'].describe())\n",
        "\n",
        "# Visualization\n",
        "  fig, axes = plt.subplots(1, 2, figsize=(12, 4))\n",
        "\n",
        "# Label distribution pie chart\n",
        "  label_dist.plot(kind='bar', ax=axes[0], color=['#2ecc71', '#e74c3c'])\n",
        "  axes[0].set_title('Stress Label Distribution')\n",
        "  axes[0].set_ylabel('Count')\n",
        "  axes[0].set_xlabel('Label')\n",
        "\n",
        "# Text length histogram\n",
        "  axes[1].hist(df['text_length'], bins=50, color='#3498db', edgecolor='black')\n",
        "  axes[1].set_title('Text Length Distribution')\n",
        "  axes[1].set_xlabel('Character Count')\n",
        "  axes[1].set_ylabel('Frequency')\n",
        "\n",
        "  plt.tight_layout()\n",
        "  plt.show()\n",
        "\n",
        "print(f\"\\n✅ Train Dataset exploration !\")\n",
        "explore_dataset(train_df_raw)\n",
        "print(f\"\\n✅ Test Dataset exploration !\")\n",
        "explore_dataset(test_df_raw)"
      ],
      "metadata": {
        "id": "D-s-heFsTE8b"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "# ============================================================================\n",
        "# CELL 5: Data Preprocessing & Validation Split\n",
        "# ============================================================================\n",
        "\n",
        "print(\"\\n\" + \"=\"*60)\n",
        "print(\"DATA PREPROCESSING\")\n",
        "print(\"=\"*60)\n",
        "\n",
        "def clean_dataframe(df, name=\"Dataset\"):\n",
        "    # Remove NaN values\n",
        "    df_clean = df.dropna(subset=['text', 'label']).copy()\n",
        "    # Remove duplicates based on text\n",
        "    df_clean = df_clean.drop_duplicates(subset=['text'])\n",
        "    # Remove very short texts\n",
        "    df_clean['text'] = df_clean['text'].astype(str).str.strip()\n",
        "    df_clean = df_clean[df_clean['text'].str.len() >= 25]\n",
        "\n",
        "    # Ensure labels are strictly integers (0 or 1)\n",
        "    df_clean['label'] = df_clean['label'].astype(int)\n",
        "\n",
        "    print(f\"✅ Cleaned {name}. Rows remaining: {len(df_clean)}\")\n",
        "    return df_clean\n",
        "\n",
        "# Clean both sets independently\n",
        "print(\"Processing Train Set...\")\n",
        "train_df_clean = clean_dataframe(train_df_raw, \"Train Set\")\n",
        "\n",
        "print(\"\\nProcessing Test Set...\")\n",
        "test_df = clean_dataframe(test_df_raw, \"Test Set\")\n",
        "\n",
        "# Create a validation set from the training pool (e.g., 15% for evaluation)\n",
        "train_df, val_df = train_test_split(\n",
        "    train_df_clean,\n",
        "    test_size=0.15,\n",
        "    stratify=train_df_clean['label'],\n",
        "    random_state=42\n",
        ")\n",
        "\n",
        "print(f\"\\n📊 Final Partition Breakdown:\")\n",
        "print(f\"   Train set:      {len(train_df)} samples ({len(train_df)/len(train_df_clean)*100:.1f}% of train file)\")\n",
        "print(f\"   Validation set: {len(val_df)} samples ({len(val_df)/len(train_df_clean)*100:.1f}% of train file)\")\n",
        "print(f\"   Test set:       {len(test_df)} samples (fully independent)\")\n",
        "\n",
        "print(f\"\\n🏷️  Train Label distribution:\\n{train_df['label'].value_counts()}\")\n",
        "print(f\"\\n🏷️  Test Label distribution:\\n{test_df['label'].value_counts()}\")"
      ],
      "metadata": {
        "id": "4lkm3qUnTOja"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "\n",
        "\n",
        "# ============================================================================\n",
        "# CELL 6: Load Model and Tokenizer\n",
        "# ============================================================================\n",
        "from google.colab import userdata\n",
        "from huggingface_hub import login\n",
        "print(\"\\n\" + \"=\"*60)\n",
        "print(\"LOADING MODEL\")\n",
        "print(\"=\"*60)\n",
        "\n",
        "# Use MentalRoBERTa base model\n",
        "\n",
        "model_name = \"mental/mental-roberta-base\"\n",
        "\n",
        "\n",
        "login(userdata.get('HF_TOKEN'))\n",
        "print(f\"\\n📥 Loading model: {model_name}\")\n",
        "tokenizer = AutoTokenizer.from_pretrained(model_name)\n",
        "model = AutoModelForSequenceClassification.from_pretrained(\n",
        "    model_name,\n",
        "    num_labels=2,  # Binary classification (stressed/not stressed)\n",
        "    id2label={0: \"Not Stressed\", 1: \"Stressed\"},\n",
        "    label2id={\"Not Stressed\": 0, \"Stressed\": 1}\n",
        ")\n",
        "\n",
        "# Move to GPU if available\n",
        "model.to(device)\n",
        "\n",
        "print(f\"✅ Model and tokenizer loaded successfully!\")\n",
        "print(f\"   Model parameters: {model.num_parameters():,}\")"
      ],
      "metadata": {
        "id": "lasOtNgnTT_E"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "\n",
        "\n",
        "# ============================================================================\n",
        "# CELL 7: Tokenize Datasets\n",
        "# ============================================================================\n",
        "\n",
        "print(\"\\n\" + \"=\"*60)\n",
        "print(\"TOKENIZING DATASETS\")\n",
        "print(\"=\"*60)\n",
        "\n",
        "def tokenize_function(examples):\n",
        "    return tokenizer(\n",
        "        examples[\"text\"],\n",
        "        padding=\"max_length\",\n",
        "        truncation=True,\n",
        "        max_length=256\n",
        "    )\n",
        "\n",
        "# Convert to Hugging Face Dataset\n",
        "train_dataset = Dataset.from_dict({\n",
        "    \"text\": train_df[\"text\"].tolist(),\n",
        "    \"label\": train_df[\"label\"].tolist()\n",
        "})\n",
        "\n",
        "val_dataset = Dataset.from_dict({\n",
        "    \"text\": val_df[\"text\"].tolist(),\n",
        "    \"label\": val_df[\"label\"].tolist()\n",
        "})\n",
        "\n",
        "test_dataset = Dataset.from_dict({\n",
        "    \"text\": test_df[\"text\"].tolist(),\n",
        "    \"label\": test_df[\"label\"].tolist()\n",
        "})\n",
        "\n",
        "print(f\"\\n🔄 Tokenizing train dataset...\")\n",
        "train_dataset = train_dataset.map(tokenize_function, batched=True, batch_size=32)\n",
        "train_dataset = train_dataset.remove_columns([\"text\"])\n",
        "\n",
        "print(f\"🔄 Tokenizing validation dataset...\")\n",
        "val_dataset = val_dataset.map(tokenize_function, batched=True, batch_size=32)\n",
        "val_dataset = val_dataset.remove_columns([\"text\"])\n",
        "\n",
        "print(f\"🔄 Tokenizing test dataset...\")\n",
        "test_dataset = test_dataset.map(tokenize_function, batched=True, batch_size=32)\n",
        "test_dataset = test_dataset.remove_columns([\"text\"])\n",
        "\n",
        "print(f\"✅ Tokenization complete!\")"
      ],
      "metadata": {
        "id": "TPSrc___TY_A"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "\n",
        "\n",
        "# ============================================================================\n",
        "# CELL 8: Define Metrics Function\n",
        "# ============================================================================\n",
        "\n",
        "def compute_metrics(eval_pred):\n",
        "    predictions, labels = eval_pred\n",
        "    predictions = np.argmax(predictions, axis=1)\n",
        "\n",
        "    accuracy = accuracy_score(labels, predictions)\n",
        "    precision, recall, f1, _ = precision_recall_fscore_support(\n",
        "        labels,\n",
        "        predictions,\n",
        "        average=\"weighted\",\n",
        "        zero_division=0\n",
        "    )\n",
        "\n",
        "    return {\n",
        "        \"accuracy\": accuracy,\n",
        "        \"precision\": precision,\n",
        "        \"recall\": recall,\n",
        "        \"f1\": f1\n",
        "    }\n",
        "\n",
        "print(\"✅ Metrics function defined!\")"
      ],
      "metadata": {
        "id": "Eax3EQToTdDd"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "\n",
        "\n",
        "# ============================================================================\n",
        "# CELL 9: Training Arguments\n",
        "# ============================================================================\n",
        "\n",
        "print(\"\\n\" + \"=\"*60)\n",
        "print(\"TRAINING SETUP\")\n",
        "print(\"=\"*60)\n",
        "\n",
        "training_args = TrainingArguments(\n",
        "    output_dir=\"./dreaddit_stress_model\",\n",
        "    num_train_epochs=3,\n",
        "    per_device_train_batch_size=16,\n",
        "    per_device_eval_batch_size=16,\n",
        "    warmup_steps=100,\n",
        "    weight_decay=0.01,\n",
        "    report_to=\"tensorboard\",\n",
        "    logging_steps=100,\n",
        "    eval_strategy=\"epoch\",\n",
        "    save_strategy=\"epoch\",\n",
        "    load_best_model_at_end=True,\n",
        "    metric_for_best_model=\"accuracy\",\n",
        "    save_total_limit=2,\n",
        "    learning_rate=2e-5,\n",
        "    seed=42,\n",
        "    gradient_accumulation_steps=1\n",
        ")\n",
        "\n",
        "print(f\"✅ Training arguments set:\")\n",
        "print(f\"   Epochs: {training_args.num_train_epochs}\")\n",
        "print(f\"   Batch size: {training_args.per_device_train_batch_size}\")\n",
        "print(f\"   Learning rate: {training_args.learning_rate}\")"
      ],
      "metadata": {
        "id": "AEDTnQNOThIw"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "\n",
        "\n",
        "# ============================================================================\n",
        "# CELL 10: Create Trainer and Train\n",
        "# ============================================================================\n",
        "\n",
        "print(\"\\n\" + \"=\"*60)\n",
        "print(\"TRAINING MODEL\")\n",
        "print(\"=\"*60)\n",
        "\n",
        "trainer = Trainer(\n",
        "    model=model,\n",
        "    args=training_args,\n",
        "    train_dataset=train_dataset,\n",
        "    eval_dataset=val_dataset,\n",
        "    compute_metrics=compute_metrics\n",
        ")\n",
        "\n",
        "print(f\"\\n🚀 Starting training...\")\n",
        "print(f\"⏱️  This will take approximately 5-15 minutes on GPU...\\n\")\n",
        "\n",
        "train_result = trainer.train()\n",
        "\n",
        "print(f\"\\n✅ Training completed!\")\n",
        "print(f\"\\n📊 Training Results:\")\n",
        "for key, value in train_result.metrics.items():\n",
        "    print(f\"   {key}: {value:.4f}\")"
      ],
      "metadata": {
        "id": "MUQrXVtfTkm2"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "\n",
        "\n",
        "# ============================================================================\n",
        "# CELL 11: Evaluate on Validation Set\n",
        "# ============================================================================\n",
        "\n",
        "print(\"\\n\" + \"=\"*60)\n",
        "print(\"VALIDATION EVALUATION\")\n",
        "print(\"=\"*60)\n",
        "\n",
        "print(f\"\\n🔍 Evaluating on validation set...\")\n",
        "eval_result = trainer.evaluate()\n",
        "\n",
        "print(f\"\\n✅ Validation Results:\")\n",
        "for key, value in eval_result.items():\n",
        "    print(f\"   {key}: {value:.4f}\")"
      ],
      "metadata": {
        "id": "3xZ2qdR7Tn8Y"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "dlwWwUF7LHJ2"
      },
      "outputs": [],
      "source": [
        "\n",
        "\n",
        "# ============================================================================\n",
        "# CELL 12: Evaluate on Test Set\n",
        "# ============================================================================\n",
        "\n",
        "print(\"\\n\" + \"=\"*60)\n",
        "print(\"TEST SET EVALUATION\")\n",
        "print(\"=\"*60)\n",
        "\n",
        "print(f\"\\n🔍 Evaluating on test set...\")\n",
        "predictions_output = trainer.predict(test_dataset)\n",
        "predictions = np.argmax(predictions_output.predictions, axis=1)\n",
        "\n",
        "# Get true labels\n",
        "test_labels = test_dataset[\"label\"]\n",
        "\n",
        "# Calculate metrics\n",
        "test_accuracy = accuracy_score(test_labels, predictions)\n",
        "test_precision, test_recall, test_f1, _ = precision_recall_fscore_support(\n",
        "    test_labels,\n",
        "    predictions,\n",
        "    average=\"weighted\",\n",
        "    zero_division=0\n",
        ")\n",
        "\n",
        "print(f\"\\n✅ Test Set Results:\")\n",
        "print(f\"   Accuracy:  {test_accuracy:.4f} ({test_accuracy*100:.2f}%)\")\n",
        "print(f\"   Precision: {test_precision:.4f}\")\n",
        "print(f\"   Recall:    {test_recall:.4f}\")\n",
        "print(f\"   F1-Score:  {test_f1:.4f}\")\n",
        "\n",
        "# Detailed classification report\n",
        "print(f\"\\n📋 Detailed Classification Report:\")\n",
        "print(classification_report(\n",
        "    test_labels,\n",
        "    predictions,\n",
        "    target_names=[\"Not Stressed\", \"Stressed\"],\n",
        "    digits=4\n",
        "))\n",
        "\n",
        "# Confusion matrix\n",
        "cm = confusion_matrix(test_labels, predictions)\n",
        "print(f\"\\n🔲 Confusion Matrix:\")\n",
        "print(cm)\n",
        "\n",
        "# Visualize confusion matrix\n",
        "fig, ax = plt.subplots(figsize=(8, 6))\n",
        "sns.heatmap(\n",
        "    cm,\n",
        "    annot=True,\n",
        "    fmt='d',\n",
        "    cmap='Blues',\n",
        "    xticklabels=['Not Stressed', 'Stressed'],\n",
        "    yticklabels=['Not Stressed', 'Stressed'],\n",
        "    ax=ax,\n",
        "    cbar=True\n",
        ")\n",
        "ax.set_ylabel('True Label')\n",
        "ax.set_xlabel('Predicted Label')\n",
        "ax.set_title('DREADDIT Stress Detection - Confusion Matrix')\n",
        "plt.tight_layout()\n",
        "plt.show()\n",
        "\n"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "\n",
        "# ============================================================================\n",
        "# CELL 13: Test on Custom Examples\n",
        "# ============================================================================\n",
        "\n",
        "print(\"\\n\" + \"=\"*60)\n",
        "print(\"TESTING ON CUSTOM EXAMPLES\")\n",
        "print(\"=\"*60)\n",
        "\n",
        "# Function to predict on new text\n",
        "def predict_stress(text):\n",
        "    inputs = tokenizer(\n",
        "        text,\n",
        "        padding=\"max_length\",\n",
        "        truncation=True,\n",
        "        max_length=256,\n",
        "        return_tensors=\"pt\"\n",
        "    )\n",
        "    inputs = {k: v.to(device) for k, v in inputs.items()}\n",
        "\n",
        "    with torch.no_grad():\n",
        "        outputs = model(**inputs)\n",
        "\n",
        "    logits = outputs.logits\n",
        "    predictions = torch.softmax(logits, dim=-1)\n",
        "    predicted_class = predictions.argmax(-1).item()\n",
        "    confidence = predictions[0, predicted_class].item()\n",
        "\n",
        "    label_names = [\"Not Stressed\", \"Stressed\"]\n",
        "\n",
        "    return {\n",
        "        \"prediction\": label_names[predicted_class],\n",
        "        \"confidence\": confidence,\n",
        "        \"probabilities\": {\n",
        "            \"Not Stressed\": predictions[0, 0].item(),\n",
        "            \"Stressed\": predictions[0, 1].item()\n",
        "        }\n",
        "    }\n",
        "\n",
        "# Test examples\n",
        "test_examples = [\n",
        "    \"I got promoted today! I'm so happy and excited!\",\n",
        "    \"I can't sleep because I'm worried about losing my job.\",\n",
        "    \"I had a wonderful day with my family.We went on a picnic after a long time. We were sitting on grass but had to move from there when a lot of crows came there.\",\n",
        "    \"It was my first result of board examination. I was extremely excited for it. When result came out, It was very good. My father was happy. But when my mother came and i told her, she only said congrats with a blank face and no expression. I was blown away. Then she saw my result and didn't even see my good marks but only noticed one subject in which i had less marks. I literaaly lost my senses. I cried and had fever for 3 days. Even now I hate her for that\",\n",
        "    \"We went to a dam for the first time. It was winter. My father told us not to go near water as it was deep. But when he went away for a moment, we went near it and touched it. It was an extremely refreshing and pleasent feeling that i will never forget in my life.\",\n",
        "    \"My boss is always criticizing my work. I'm anxious all the time.\"\n",
        "]\n",
        "\n",
        "print(f\"\\n🧪 Testing on custom examples:\\n\")\n",
        "\n",
        "for text in test_examples:\n",
        "    result = predict_stress(text)\n",
        "    print(f\"Text: \\\"{text}\\\"\")\n",
        "    print(f\"   Prediction: {result['prediction']}\")\n",
        "    print(f\"   Confidence: {result['confidence']:.2%}\")\n",
        "    print(f\"   Probabilities: {result['probabilities']}\")\n",
        "    print()"
      ],
      "metadata": {
        "id": "mCyj2D02Tu46"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "\n",
        "# ============================================================================\n",
        "# CELL 14: Save Model and Tokenizer\n",
        "# ============================================================================\n",
        "\n",
        "print(\"\\n\" + \"=\"*60)\n",
        "print(\"SAVING MODEL\")\n",
        "print(\"=\"*60)\n",
        "\n",
        "output_dir = \"./dreaddit_stress_model_final\"\n",
        "\n",
        "print(f\"\\n💾 Saving model to {output_dir}...\")\n",
        "model.save_pretrained(output_dir)\n",
        "tokenizer.save_pretrained(output_dir)\n",
        "\n",
        "print(f\"✅ Model and tokenizer saved!\")\n",
        "\n",
        "# Save training results to JSON\n",
        "results_dict = {\n",
        "    \"model\": model_name,\n",
        "    \"task\": \"Binary Stress Detection (DREADDIT)\",\n",
        "    \"test_accuracy\": float(test_accuracy),\n",
        "    \"test_precision\": float(test_precision),\n",
        "    \"test_recall\": float(test_recall),\n",
        "    \"test_f1\": float(test_f1),\n",
        "    \"test_samples\": len(test_labels),\n",
        "    \"confusion_matrix\": cm.tolist(),\n",
        "    \"timestamp\": datetime.now().isoformat()\n",
        "}\n",
        "\n",
        "with open(f\"{output_dir}/results.json\", \"w\") as f:\n",
        "    json.dump(results_dict, f, indent=2)\n",
        "\n",
        "print(f\"✅ Results saved to results.json\")\n"
      ],
      "metadata": {
        "id": "eI0gvEvlT7ip"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "# ============================================================================\n",
        "# CELL 15: Upload Model Directly to Hugging Face Hub\n",
        "# ============================================================================\n",
        "\n",
        "print(\"\\n\" + \"=\"*70)\n",
        "print(\"UPLOADING TO HUGGING FACE HUB\")\n",
        "print(\"=\"*70)\n",
        "\n",
        "import time\n",
        "from google.colab import userdata\n",
        "from huggingface_hub import HfApi, login, logout, upload_folder\n",
        "\n",
        "# Step 1: Wipe out the old cached read-only token session\n",
        "try:\n",
        "    logout()\n",
        "    print(\"logged out\")\n",
        "except:\n",
        "    pass\n",
        "\n",
        "# Step 2: Grab your write token and force-overwrite the session\n",
        "print(\"\\n🔑 Fetching HF_WTOKEN from Colab Secrets...\")\n",
        "hf_token = userdata.get('HF_WTOKEN').strip()\n",
        "\n",
        "print(\"🔐 Logging into Hugging Face Hub with Write access...\")\n",
        "login(token=hf_token)\n",
        "print(\"✅ Successfully logged in to HF Hub!\")\n",
        "\n",
        "# Step 3: Get username from HF\n",
        "print(\"\\n👤 Getting your HF username...\")\n",
        "api = HfApi()\n",
        "user_info = api.whoami(token=hf_token)\n",
        "username = user_info['name']\n",
        "print(f\"✅ Your username: {username}\")\n",
        "\n",
        "\n",
        "# Step 6: Upload model files\n",
        "print(f\"\\n📤 Uploading model files to HF Hub...\")\n",
        "print(f\"   This may take 2-5 minutes depending on internet speed...\")\n",
        "\n",
        "try:\n",
        "\n",
        "    # Upload entire folder\n",
        "    start_time = time.time()\n",
        "    full_repo_id=\"hafsaimranattaria7115/stress-detector-finetuned\"\n",
        "    upload_folder(\n",
        "        folder_path=\"./dreaddit_stress_model_final\",\n",
        "        repo_id=full_repo_id,\n",
        "        repo_type=\"model\",\n",
        "        token=hf_token,\n",
        "        commit_message=\"Add fine-tuned DREADDIT stress detection model\"\n",
        "    )\n",
        "\n",
        "    elapsed_time = time.time() - start_time\n",
        "    print(f\"\\n✅ Upload completed in {elapsed_time:.1f} seconds!\")\n",
        "\n",
        "except Exception as e:\n",
        "    print(f\"❌ Upload failed: {str(e)}\")\n",
        "    print(\"\\n   Troubleshooting:\")\n",
        "    print(\"   - Check internet connection\")\n",
        "    print(\"   - Make sure token is valid\")\n",
        "    print(\"   - Try again in a moment\")\n",
        "\n",
        "# Step 7: Verify upload\n",
        "print(f\"\\n🔍 Verifying upload...\")\n",
        "\n",
        "try:\n",
        "    # List files in repo\n",
        "    files = api.list_repo_files(repo_id=full_repo_id, repo_type=\"model\", token=hf_token)\n",
        "\n",
        "    print(f\"\\n✅ Files uploaded to HF Hub:\")\n",
        "    for file in files:\n",
        "        print(f\"   ✓ {file}\")\n",
        "\n",
        "except Exception as e:\n",
        "    print(f\"⚠️  Could not verify: {str(e)}\")\n",
        "\n",
        "# Step 8: Print next steps\n",
        "print(\"\\n\" + \"=\"*70)\n",
        "print(\"✅ MODEL UPLOADED SUCCESSFULLY!\")\n",
        "print(\"=\"*70)\n",
        "\n",
        "print(f\"\"\"\n",
        "📍 YOUR MODEL IS NOW ON HUGGING FACE HUB:\n",
        "   Repo: https://huggingface.co/{full_repo_id}\n",
        "   Privacy: PRIVATE (only you can access)\n",
        "   Token: Required to use via API\n",
        "\n",
        "📝 USAGE IN BACKEND:\n",
        "\n",
        "   from huggingface_hub import InferenceClient\n",
        "\n",
        "   client = InferenceClient(\n",
        "       model=\"{full_repo_id}\",\n",
        "       token=\"[YOUR_HF_TOKEN_HERE]\" # Replaced for security\n",
        "   )\n",
        "\n",
        "   result = client.text_classification(\"I am stressed about work\")\n",
        "   # Returns: [{{\"label\": \"Stressed\", \"score\": 0.92}}]\n",
        "\n",
        "🎯 NEXT STEPS:\n",
        "   1. Copy your repo ID: {'hafsaimranattaria7115/stress-detector-fi...'}\n",
        "   2. Save your API token (keep it SECRET!)\n",
        "   3. Repeat this process for Emotion model\n",
        "   4. Use both models in FastAPI backend\n",
        "   5. Deploy to Railway\n",
        "\n",
        "💡 SECURITY TIPS:\n",
        "   ✓ Never share your token\n",
        "   ✓ Use environment variables in production\n",
        "   ✓ Rotate token periodically\n",
        "   ✓ Keep repos private\n",
        "\n",
        "🚀 Ready to use in production!\n",
        "\"\"\")\n",
        "\n",
        "print(\"=\"*70)\n"
      ],
      "metadata": {
        "id": "H6S_Eg85UGmY"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "\n",
        "# ============================================================================\n",
        "# CELL 16: Summary (Original)\n",
        "# ============================================================================\n",
        "\n",
        "print(\"\\n\" + \"=\"*70)\n",
        "print(\"DREADDIT STRESS DETECTION - TRAINING SUMMARY\")\n",
        "print(\"=\"*70)\n",
        "\n",
        "print(f\"\"\"\n",
        "🎯 MODEL: MentalRoBERTa (\"mental/mental-roberta-base\")\n",
        "📊 TASK: Binary Stress Classification\n",
        "\n",
        "📈 RESULTS:\n",
        "   Test Accuracy:  {test_accuracy*100:.2f}%\n",
        "   Precision:      {test_precision:.4f}\n",
        "   Recall:         {test_recall:.4f}\n",
        "   F1-Score:       {test_f1:.4f}\n",
        "\n",
        "📁 FILES GENERATED:\n",
        "   - dreaddit_stress_model_final/ (model directory)\n",
        "   - results.json (metrics)\n",
        "\n",
        "✅ UPLOAD STATUS:\n",
        "   Model uploaded directly to Hugging Face Hub ✓\n",
        "   Repository: stress-detector-finetuned (PRIVATE)\n",
        "   Ready to use via HF Inference API\n",
        "\n",
        "🚀 You're ready for production!\n",
        "\"\"\")\n",
        "\n",
        "print(\"=\"*70)"
      ],
      "metadata": {
        "id": "Gkq9eFzd6bmU"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}